### ISSUE TITLE
Handling token expiration without page refresh

### ISSUE THREAD

**Issue by dibeesh** [auth0-community/auth0-socketio-jwt#108]
Hi, 
Implemented socketio-jwt in one of my project and its working great. 

I have one doubt, i have set my token an expiry of 5mnt, so am expecting my browser client will get an token expired alert without page refresh when its connected to server. But here its only firing "unauthorized" event on page refresh.

 Can you plz look in to it? Is there anything missed in my following code?

**serve side**

io.sockets
  .on('connection', socketioJwt.authorize({
    secret: 'your secret or public key',
    timeout: 15000 // 15 seconds to send the authentication message
  })).on('authenticated', function(socket) {
    //this socket is authenticated, we are good to handle more events from it.
    console.log('hello! ' + socket.decoded_token.name);
  });
**Client side:**

var socket = io.connect('http://localhost:9000');
socket.on('connect', function () {
  socket
    .emit('authenticate', {token: jwt}) //send the jwt
    .on('authenticated', function () {
      //do other things
    })
    .on('unauthorized', function(msg) {
      alert("sorry your token expired");
      console.log("unauthorized: " + JSON.stringify(msg.data));
      throw new Error(msg.data.type);
    })
});

**Comment by remolueoend** [comment]
As far as I understand, the token is only validated once by the server when the initial websocket message containing the token is sent by the client (`emit('authenticate', {token: jwt})`). After that, the websocket connection is kept alive as long as you keep your server running and do not refresh your browser (using your code above). The server will not close the connection when the token expires, nor will the client. But as soon as you refresh your browser and your token expired in the meantime, the server will refuse to connect again.

This issue sounds more like a feature request. What do you think?

**Comment by dibeesh** [comment]
Ya am also thinking that way. 
Can you the image(https://www.screencast.com/t/3f1IWUVjvV). I can see there is ping is happening from client side to server side in every 2 or 3 sec. You can see the request in browser console (see screenshot link). 

My doubt is that can i get this ping event in server side, if so i can check the expiry of token in server side.
