### ISSUE TITLE
Invalid token type

### ISSUE THREAD

**Issue by giovannyreyeso** [auth0-community/auth0-socketio-jwt#113]
## Now i am writing a project and have 3 parts:
 One: a frontend with angularjs.
Two:  a backend write in C#
Three: a middleware socket server (node js, socket io) handle real time notification)

- When user sign in the app backend (C#) authenticate an create a jwt token and send to frontend
- When user is in frontend part (AngularJS) connect and authenticate to socket server
**- In this point it's all fine..**
- But when the backend(C#)  try to connect and authenticate (try send a notification message) in socket server get a unauthorized and get this error:
"Invalid token type " and i can't understand why

**Comment by Idicious** [comment]
I had this problem as well, the way I got it to work was: 

- For the signing credentials in c#:
SigningCredentials = new SigningCredentials(new SymmetricSecurityKey(symmetricKey), SecurityAlgorithms.HmacSha256Signature)

At this point it still would not authenticate, the part I was missing to change the socket.io server to:

io.on('connection', socketioJwt.authorize({
        secret: **Buffer(secret, 'base64')**,
        timeout: 15000 // 15 seconds to send the authentication message
    }));
At first I only had secret: secret.

**Comment by giovannyreyeso** [comment]
Thanks @Idicious  i will check this soon ;)
