### ISSUE TITLE
types are not working in typescript

### ISSUE THREAD

**Issue by kerolloz** [auth0-community/auth0-socketio-jwt#159]
### Description

Types don't exist in the npm package.

### Expected behaviour

`types` folder should exist. 

### Actual behaviour 

TypeScript complains that there are no types for `socketio-jwt`. 
TypeScript says that I should install `@types/socketio-jwt`.

### Language / Framework Versions

1. **TypeScript**
2. **Express**

### Screenshots

![Screenshot 2019-09-03 22:24:43](https://user-images.githubusercontent.com/36763164/64206029-aaa88600-ce99-11e9-88d5-fc29360ba366.png)

**Comment by kerolloz** [comment]
@beardaway
@Annyv2
@Amialc 
@pose
@Root-Core

**Comment by Root-Core** [comment]
Which version of typescript do you use?
Types do exist: [types/index.d.ts](https://github.com/auth0-community/auth0-socketio-jwt/blob/master/types/index.d.ts)

**Comment by williamflynt** [comment]
@Root-Core I think NPM is up to date now.

**Comment by Root-Core** [comment]
That seems to be the case.
@kerolloz - If the problem is now completely solved for you, consider closing the issue. 👍

**Comment by kerolloz** [comment]
Thank you @Root-Core.
The issue has been fixed.
