### ISSUE TITLE
New release on npm

### ISSUE THREAD

**Issue by Root-Core** [auth0-community/auth0-socketio-jwt#163]
Hello there,

it would be nice to know, who is in charge of releasing new versions of the `socketio-jwt` package on npm.

The npm package is 3 years old and the code improved quite a bit since.
It still goes strong with ~10.000 weekly downloads.

cc: @beardaway @jfromaniello

**Comment by beardaway** [comment]
Hey there @Root-Core !

To be totally honest I'm not sure if I have mentioned it already but pretty much all repos that are under auth0-community GitHub org have been kinda unnaturally outsourced to community developers (because of Auth0 bandwidth issues some time ago), which means no AUth0 employee for now is officially taking care of them as you see the PRs and issues are sometimes quite outdated. So to answer your questions there is no such person as of now who is responsible for releasing new versions of tools hosted here unfortunately.

**Comment by Root-Core** [comment]
Hello,

I totally got that these repos are now community driven, which is a good thing.
Otherwise these repos would be abandoned.

I just wondered, as most of them are samples and not really released as an package on npm how you guys handle it. Nobody requests you to actively maintain the repos, but it would be nice if there was a mechanism in place to handle the release of new packages.

The community contributions are more or less lost, if the community has no way to trigger a release.
No rant, just curious. 😇

**Comment by therealwolf42** [comment]
@Root-Core is making a valid point. Is there an alternative or a way to contact Auth0 so they can either update the package or delegate that privilege to someone else? My guess is that those countless commits over the last 3 years shouldn't be for nothing.

**Comment by beardaway** [comment]
Hey there!

Thanks for providing all that feedback! Let me bring this thread to attention of a team that will be potentially responsible for that repos.

**Comment by laviddichterman** [comment]
Any update here? Would really like to be able to pull a new version of this package and not basically have it forked locally.

**Comment by ssnxd** [comment]
meanwhile, if anyone here needs the latest code I have a fork here: https://github.com/ssnxd/auth0-socketio-jwt it's up to date with the master branch and it's available in npm to.

`npm install @ssnxd/socketio-jwt`

**Comment by eskemojoe007** [comment]
Yeah...I just ran across this as I dug into the code and it should have been doing what I intended, but the NPM module is WAY out of date.  We need to be able to publish this to NPM.

**Comment by laviddichterman** [comment]
Sent the auth0 folks a tweet, they said they'll look into it. Hopefully it gets some traction.

**Comment by jfromaniello** [comment]
I reviewed all the commits and found mostly backward compatible features and fixes for tests and readme. So I published a new minor version to npm: `socketio-jwt@4.6.0`.

Sorry about that and thank you for bringing this to our attention.

**Comment by JimCMorrison** [comment]
@jfromaniello updated the version on npm, closing Github issue.

**Comment by ankon** [comment]
@jfromaniello I'm not sure where the sources for that 4.6.0 are now -- there seem to be no changes in this repository? In any case, could you have a look at #168 -- 4.6.0 from npm contains some leftover `.git` directory which breaks things in ugly ways. Thanks a lot!
