### ISSUE TITLE
Handshake : false Error

### ISSUE THREAD

**Issue by stephengardner** [auth0-community/auth0-socketio-jwt#27]
When using handshake : false I'm getting an error here:

``` javascript
var Namespace = Object.getPrototypeOf(server.server.sockets).constructor;
```

because "this.server" is undefined within noQsMethod.

I've got everything set up and working great.  I actually have a real simple method set up for using optional authentication by setting a "required" option to false.  But it's not using noQsMethod because it's not operating as intended.

set up socketio and again, it's working, just not with handshake : false.  There's not much documentation so thought I'd ask.

``` javascript
...

var app = express();

// Setup server
var server = require('http').createServer(app);
...
var socketio = require('socket.io')(server, {
    serveClient: (config.env === 'production') ? false : true
    , path: '/socket.io-client'
});
var socketioJwt = require('socketio-jwt');
socketio.use(socketioJwt.authorize({
        secret: config.secrets.session,
        handshake: false
    }));
```

**Comment by tmedetbekov** [comment]
+1 I have the exact same issue
