### ISSUE TITLE
Retrieve token from cookies?

### ISSUE THREAD

**Issue by s992** [auth0-community/auth0-socketio-jwt#57]
One of the recommendations in [this article](https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage/) is to store the JWT token as an `HttpOnly` cookie. Would you consider a pull request to add the ability to read the token from a cookie when authenticating in the handshake?

If you would, I could use a little guidance. Currently, it appears that precedence is given to tokens passed in the query string. That is, it first searches in the authorization header, but will overwrite the token found in that header if a token is found in a query string. For an implementation using cookies, where would you prefer the cookie fall into this hierarchy?

**Comment by s992** [comment]
An alternative would be allowing the user to specifiy a `getToken` function, similar to how express-jwt does it. Personally, I prefer this option because it allows more flexibility and doesn't marry this project to a cookie parsing library.

I'd be happy to work on a pull request for either option, if you'd be open to that.

**Comment by ZiCog** [comment]
I just came here for the same reason. I read that same article re: cookies vs webstorage for jwt and decided it was a good idea. So I implemented JWT in HttpOnly cookie in my experimental server/client.

Then I realized my socket.io authorization was not going to work!

Is there a nice way to work around this in lieu of any fix here?

**Comment by s992** [comment]
@ZiCog I have a fork where I've implemented a custom `getToken` function, which should work with cookies (assuming you have a cookie parsing middleware such as [socket.io-cookie-parser](https://www.npmjs.com/package/socket.io-cookie-parser)). 

My fork is at https://github.com/s992/socketio-jwt. I'm not currently using it in any production applications, so I'd recommend giving it a thorough testing before rolling it out. :)

**Comment by ZiCog** [comment]
Ah, great. I'll give that a go. My current experimental client/server is far away from production use.

**Comment by ZiCog** [comment]
@s992 

Your s992/socketio-jwt works!

After many hours fritzing around trying to fit this into my app I gave that up and created the simplest possible client/server (based on the socketio-jwt example).

It works but I don't like my solution. I could not figure out gow to get at the cookie from inside getToken(). I ended up with a global token that is extracted by socket.io-cookie-parser in an authorization callback. Like so:

    var jwtSecret = 'I am a secret, keep me.';
    var profile = {
        username: 'guest',
        email:    'guest@example.com',
        id:       123
    };
    // Set the profile in the JSON web token
    var accessToken = jwt.sign(profile, jwtSecret, { expiresIn : 60 * 60 * 24});

    app.get('/', function (req, res) {
        // Send the token in a cookie
        new Cookies(req,res).set('accessToken', accessToken, {
            httpOnly: true,      // Javascript cannnot read cookie
            secure:   false      // Send over HTTPS only for your production environment
        });
        res.sendFile(__dirname + '/index.html');
    });

    io.use(cookieParser());

    var accessTokenNow = null;

    io.use(function authorization(socket, next) {
        // cookies are available in:
        // 1. socket.request.cookies
        // 2. socket.request.signedCookies (if using a secret)
        accessTokenNow = socket.request.cookies.accessToken;
        next();
    });

    io.of('/ws/chat')
    .on('connection', socketioJwt.authorize({
        secret:  jwtSecret,
        timeout: 15000,           // 15 seconds to send the authentication message
        getToken: function () {
            return accessTokenNow;
        }
    }))
    .on('authenticated', function (socket) {
        console.log('Chat connected & authenticated: ', socket.decoded_token);
        socket.on('chat message', function (data) {
            console.log('Chat message:', data);
            socket.emit('chat message', data);
        });
    });


Needless to say I don't like that global token. What can I do about it ?

My little test is here: https://bitbucket.org/zicog/propanel/src/4c7690cb4b22/socketio-jwt-test/?at=master

**Comment by s992** [comment]
I forked your repo on Bitbucket and I'll take a look at it after work today. I also copied your comment over onto an issue on my fork so that we don't clutter this ticket trying to troubleshoot: https://github.com/s992/socketio-jwt/issues/1

**Comment by gonsfx** [comment]
@ntotten @jfromaniello i hope someone reads this. when using jwt authentication with http and websockets, would it still be a good idea to store the jwt in a httpOnly cookie? if so - how would you handle websocket auth?

**Comment by LaurensRietveld** [comment]
I'm having this same issue. Only think I can come up with is an API call that re-issues a very shortlived JWT (e.g. 10 secs). That token can then be used to authenticate over socketio. Not a very clean solution though as it requires another route. You'd want to make sure that you cannot re-issue one of these short-lived jwt's though

**Comment by Root-Core** [comment]
@beardaway This issue should be closed, as #134 is merged. (Sorry for spamming you. 😇)
