### ISSUE TITLE
Question: io.use checks token on connection/reconnection, but on every event token is not checked

### ISSUE THREAD

**Issue by Kiura** [auth0-community/auth0-socketio-jwt#75]
Is it secure enough to check token on connection? do I need to check token on every event?
E.g. 
check on every getNews event

``` Node
socket.on("getNews", function(data, callback){
    // check token and if valid return news via callback
});
```

vs
check on connection/reconnection

``` Node
io.use(function(socket, next) { // using general example not socketio-jwt
    // check token and if valid proceed
});
```

One more question, how to know which user the particular token belongs to? One way would be to add id to payload, however, is it best practice?

**Comment by jcuypers** [comment]
Its based on your requirements, I guess.   Functionally, socket.io compares to a house with one entrance door compared to an API which can be seen as a house with many entrance doors.  In the case of an API you would want to shield off every door (or most of the doors) with token protection.   For socket.io, you might want to shield off the front door, and based on whether or not you want to control access to some services inside (create some internal doors) by checking tokens and potentially   I guess it only makes sense to check on every event when you need to allow precise access to certain services and different people can have different rights in other scenarios protecting one front door (with building some extra fences if required) will be enough.

**Comment by jcuypers** [comment]
one other item maybe.  if the token gets compromised, it would be the same key for all the doors anyway
