### ISSUE TITLE
Question/Feature Request: How to catch/log authentication errors on the server?

### ISSUE THREAD

**Issue by jghaines** [auth0-community/auth0-socketio-jwt#84]
From the given example, errors (e.g. unauthorized) are silently swallowed on the server. Would be nice to at least log them.

I found the 'unauthorized' event on the client and have created pull requests to include this in the examples.

**Comment by FaizanZahid** [comment]
yes i want to catch the unauthorised event on the server side so i can confirm that fake requests/users r being denied and i can log them.
